/**
 * Wails API wrapper for LAN Commander.
 * All functions call the Go backend via Wails bindings.
 * These bindings are auto-generated by Wails in frontend/wailsjs/go/main/App.js
 */

import type { AgentInfo } from '../stores/agents';

// We use dynamic imports to safely handle missing bindings during dev
let App: Record<string, (...args: unknown[]) => Promise<unknown>> = {};

try {
	// Dynamic import - Vite handles this
	const appModule = await import('../../../wailsjs/go/main/App.js');
	App = appModule as unknown as typeof App;
} catch {
	console.warn('Wails App bindings not available yet');
}

async function callBinding(name: string, ...args: unknown[]): Promise<unknown> {
	if (!App[name]) {
		throw new Error(`Wails binding "${name}" not available. Run 'wails generate module' first.`);
	}
	return App[name](...args);
}

// --- Agent Management ---

/**
 * The Go backend serializes AgentInfo with snake_case tags (`last_seen`,
 * `system_info`). The frontend uses camelCase, so we normalize here at the
 * boundary rather than letting `undefined` leak into the components.
 */
function normalizeAgent(raw: Record<string, unknown>): AgentInfo {
	return {
		id: String(raw.id ?? ''),
		host: String(raw.host ?? ''),
		port: Number(raw.port ?? 0),
		name: String(raw.name ?? ''),
		os: String(raw.os ?? ''),
		arch: String(raw.arch ?? ''),
		connected: Boolean(raw.connected),
		secure: Boolean(raw.secure),
		lastSeen: (raw.last_seen ?? raw.lastSeen ?? '') as string,
		systemInfo: (raw.system_info ?? raw.systemInfo ?? null) as AgentInfo['systemInfo'],
		systemInfoError: null,
		cpuHistory: [],
	};
}

export async function getAgents(): Promise<AgentInfo[]> {
	const raw = (await callBinding('GetAgents')) as Record<string, unknown>[] | null;
	if (!Array.isArray(raw)) return [];
	return raw.map(normalizeAgent);
}

export async function connectAgent(host: string, port: number, authToken: string = '', secure: boolean = false) {
	if (secure) return connectAgentSecure(host, port, authToken);
	return callBinding('ConnectAgent', host, port, authToken);
}

export async function connectAgentSecure(
	host: string,
	port: number,
	authToken: string = '',
	caFile: string = '',
	serverName: string = '',
) {
	return callBinding('ConnectAgentSecure', host, port, authToken, caFile, serverName);
}

export async function disconnectAgent(agentId: string) {
	return callBinding('DisconnectAgent', agentId);
}

// --- Commands ---
export async function execCommand(agentId: string, command: string, timeout: number = 0) {
	return callBinding('ExecCommand', agentId, command, timeout);
}

export async function execCommandMulti(agentIds: string[], command: string, timeout: number = 0) {
	return callBinding('ExecCommandMulti', agentIds, command, timeout);
}

// --- Files ---
export async function listDir(agentId: string, path: string) {
	return callBinding('ListDir', agentId, path);
}

// --- System ---
export async function getSystemInfo(agentId: string) {
	return callBinding('GetSystemInfo', agentId);
}

export async function requestScreenshot(agentId: string) {
	return callBinding('RequestScreenshot', agentId);
}

export async function transferFile(agentId: string, remotePath: string, localPath: string) {
	return callBinding('TransferFile', agentId, remotePath, localPath);
}

function callTransferBinding(name: string, ...args: unknown[]): Promise<unknown> {
	const generatedBinding = App[name];
	if (generatedBinding) return generatedBinding(...args);
	const nativeBinding = (globalThis as { go?: { main?: { App?: Record<string, (...values: unknown[]) => Promise<unknown>> } } }).go?.main?.App?.[name];
	if (nativeBinding) return nativeBinding(...args);
	return Promise.reject(new Error(`Wails binding "${name}" not available`));
}

export async function downloadFile(agentId: string, remotePath: string) {
	return callTransferBinding('DownloadFile', agentId, remotePath);
}

export async function uploadFile(agentId: string, remoteDirectory: string) {
	return callTransferBinding('UploadFile', agentId, remoteDirectory);
}

// --- Wake-on-LAN ---
export async function wakeOnLAN(macAddr: string, broadcastIP: string = '255.255.255.255') {
	return callBinding('WakeOnLAN', macAddr, broadcastIP);
}

// --- Sessions ---
export async function getSessions() {
	return callBinding('GetSessions');
}

export async function saveSession(host: string, port: number, name: string, authToken: string = '', secure: boolean = false) {
	if (secure) return saveSessionSecure(host, port, name, authToken);
	return callBinding('SaveSession', host, port, name, authToken);
}

export async function saveSessionSecure(
	host: string,
	port: number,
	name: string,
	authToken: string = '',
	caFile: string = '',
	serverName: string = '',
) {
	return callBinding('SaveSessionSecure', host, port, name, authToken, caFile, serverName);
}

export async function deleteSession(id: number) {
	return callBinding('DeleteSession', id);
}

// --- Scripts ---
export async function runScript(agentId: string, scriptName: string, scriptContent: string) {
	return callBinding('RunScript', agentId, scriptName, scriptContent);
}

export async function getScripts() {
	return callBinding('GetScripts');
}

export async function saveScript(name: string, content: string) {
	return callBinding('SaveScript', name, content);
}

// --- Audit ---
export async function getAuditLogs(limit: number = 100) {
	return callBinding('GetAuditLogs', limit);
}

export async function chooseSavePath(defaultFilename: string) {
	return callBinding('ChooseSavePath', defaultFilename);
}
