// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConnectAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['ConnectAgent'](arg1, arg2, arg3);
}

export function ConnectAgentSecure(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ConnectAgentSecure'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DisconnectAgent(arg1) {
  return window['go']['main']['App']['DisconnectAgent'](arg1);
}

export function DownloadFile(arg1, arg2) {
  return window['go']['main']['App']['DownloadFile'](arg1, arg2);
}

export function ExecCommand(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecCommand'](arg1, arg2, arg3);
}

export function ExecCommandMulti(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecCommandMulti'](arg1, arg2, arg3);
}

export function GetAgents() {
  return window['go']['main']['App']['GetAgents']();
}

export function GetAuditLogs(arg1) {
  return window['go']['main']['App']['GetAuditLogs'](arg1);
}

export function GetScripts() {
  return window['go']['main']['App']['GetScripts']();
}

export function GetSessions() {
  return window['go']['main']['App']['GetSessions']();
}

export function GetSystemInfo(arg1) {
  return window['go']['main']['App']['GetSystemInfo'](arg1);
}

export function ListDir(arg1, arg2) {
  return window['go']['main']['App']['ListDir'](arg1, arg2);
}

export function RequestScreenshot(arg1) {
  return window['go']['main']['App']['RequestScreenshot'](arg1);
}

export function RunScript(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunScript'](arg1, arg2, arg3);
}

export function SaveScript(arg1, arg2) {
  return window['go']['main']['App']['SaveScript'](arg1, arg2);
}

export function SaveSession(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveSession'](arg1, arg2, arg3, arg4);
}

export function SaveSessionSecure(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['SaveSessionSecure'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function TransferFile(arg1, arg2, arg3) {
  return window['go']['main']['App']['TransferFile'](arg1, arg2, arg3);
}

export function UploadFile(arg1, arg2) {
  return window['go']['main']['App']['UploadFile'](arg1, arg2);
}

export function UploadFileFromPath(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadFileFromPath'](arg1, arg2, arg3);
}

export function WakeOnLAN(arg1, arg2) {
  return window['go']['main']['App']['WakeOnLAN'](arg1, arg2);
}
