// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {protocol} from '../models';
import {client} from '../models';
import {audit} from '../models';
import {scripting} from '../models';
import {session} from '../models';

export function ChooseSavePath(arg1:string):Promise<string>;

export function ConnectAgent(arg1:string,arg2:number,arg3:string):Promise<void>;

export function ConnectAgentSecure(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string):Promise<void>;

export function DeleteSession(arg1:number):Promise<void>;

export function DisconnectAgent(arg1:string):Promise<void>;

export function DownloadFile(arg1:string,arg2:string):Promise<void>;

export function ExecCommand(arg1:string,arg2:string,arg3:number):Promise<protocol.CommandResultPayload>;

export function ExecCommandMulti(arg1:Array<string>,arg2:string,arg3:number):Promise<Record<string, protocol.CommandResultPayload>>;

export function GetAgents():Promise<Array<client.AgentInfo>>;

export function GetAuditLogs(arg1:number):Promise<Array<audit.Entry>>;

export function GetScripts():Promise<Array<scripting.Script>>;

export function GetSessions():Promise<Array<session.Session>>;

export function GetSystemInfo(arg1:string):Promise<protocol.SystemInfoPayload>;

export function ListDir(arg1:string,arg2:string):Promise<protocol.DirContentsPayload>;

export function RequestScreenshot(arg1:string):Promise<protocol.ScreenshotDataPayload>;

export function RunScript(arg1:string,arg2:string,arg3:string):Promise<protocol.CommandResultPayload>;

export function SaveScript(arg1:string,arg2:string):Promise<void>;

export function SaveSession(arg1:string,arg2:number,arg3:string,arg4:string):Promise<void>;

export function SaveSessionSecure(arg1:string,arg2:number,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function TransferFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function UploadFile(arg1:string,arg2:string):Promise<void>;

export function UploadFileFromPath(arg1:string,arg2:string,arg3:string):Promise<void>;

export function WakeOnLAN(arg1:string,arg2:string):Promise<void>;
